version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            git submodule update --init --recursive
            export HOME=/home/circleci/project
            bash setup.sh test
