#!/bin/bash

# This script converts jupyter notebook to PDF

set -eu

tmpdir=$(mktemp -d)
ln -s $(pwd)/$1 $tmpdir/
cd $tmpdir

cat <<EOD > article.tplx
% Default to the notebook output style
((* if not cell_style is defined *))
    ((* set cell_style = 'style_ipython.tplx' *))
((* endif *))

% Inherit from the specified cell style.
((* extends cell_style *))

%===============================================================================
% Latex Article
%===============================================================================

((* block docclass *))
\documentclass{ltjsarticle}
((* endblock docclass *))

((* block input_group *))
    ((*- if cell.metadata.get('nbconvert', {}).get('show_code', False) -*))
        ((( super() )))
    ((*- endif -*))
((* endblock input_group *))
EOD

FILENAME=$(basename $1 .ipynb)
jupyter nbconvert --to latex --template article.tplx $1
lualatex ${FILENAME}.tex

cd -
cp $tmpdir/${FILENAME}.pdf .
