#!/local/bin/env zsh
#
bindkey -e
# avoid nomatch error when *, []
setopt nonomatch 
# enable # comments in interactive mode
setopt interactivecomments
# cd -[tab] suggests directories
setopt auto_pushd
setopt pushd_ignore_dups

setopt extended_glob
#setopt prompt_subst

# completion
autoload -U compinit; compinit
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
setopt complete_aliases

# history
setopt share_history
setopt extended_history 
export HISTFILE=${HOME}/.histfile
setopt hist_ignore_all_dups
export HISTSIZE=10000 # on memory
export SAVEHIST=10000
disable r # use ctrl+r instead


# PATH
export PATH="${PATH}:${HOME}/.dotfiles/bin"

# see http://www.sirochro.com/note/terminal-zsh-prompt-customize/
autoload -Uz colors # black red green yellow blue magenta cyan white
colors

# set aliases or replace commands
alias ls='ls -GF'
alias la='ls -la'
alias lh='ls -lh'

if (( $+commands[jupyter] )); then
    alias jup='jupyter lab'
fi

if (( $+commands[direnv] )); then
    # recommended
    alias tmux='direnv exec / tmux'
fi
alias tma='tmux a'

if (( $+commands[nvim] )); then
    alias vim='nvim'
fi

if (( $+commands[bat] )); then
    alias cat='bat'
fi

if (( $+commands[exa] )); then
    alias ls='exa --git'
fi

if (( $+commands[hub] )); then
    alias git='hub'
fi

# functions
mc(){
    mkdir $1
    cd $1
    echo `pwd`
}

if (( $+commands[peco] )); then
    alias -g P='| peco'
    function peco-select-history() {
        BUFFER=$(fc -l -r -n 1 | peco --query "$LBUFFER")
        CURSOR=$#BUFFER
        zle redisplay
    }
    zle -N peco-select-history
    bindkey '^r' peco-select-history
    
    function peco-src() {
        local selected_dir=$(ghq list | peco --query "$LBUFFER")
        if [ -n "$selected_dir" ]; then
            BUFFER="cd ${HOME}/.ghq/${selected_dir}"
            zle accept-line
        fi
        zle redisplay
    }
    zle -N peco-src
    bindkey '^g' peco-src
fi

if (( $+commands[direnv] )); then
    export EDITOR=nvim
    eval "$(direnv hook zsh)"
fi

# plugins
fpath=( /usr/local/share/zsh-completions $fpath )
#fpath=( "${HOME}/.dotfiles/zsh" $fpath )

fpath+=${HOME}/.dotfiles/zsh/pure
autoload -U promptinit; promptinit
prompt pure
source ${HOME}/.dotfiles/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=250'
