[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'derekwyatt/vim-scala'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'lervag/vimtex'

[[plugins]]
repo = 'scrooloose/nerdtree'
