[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo ='Shougo/defx.nvim'
on_cmd = 'Defx'

[[plugins]]
repo = 'Townk/vim-autoclose'

#[[plugins]]
#repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'joshdick/onedark.vim'
