[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft =  'rust'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = 'markdown'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'w0rp/ale'
on_ft = ['python', 'cpp']
hook_source = '''
    "ale
    let g:ale_linters = {
    \ 'python': ['autopep8', 'pyre'],
    \ 'cpp': ['clangd'],
    \}
    let g:ale_fixers = {
    \ 'python': ['autopep8'],
    \}
    nnoremap <C-m> :ALEFix<CR>
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = ['deoplete.nvim']
on_ft = ['python']
on_i = 1
hook_source = '''
    let g:deoplete#sources#jedi#statement_length = 0
    let g:deoplete#sources#jedi#short_types = 0
    let g:deoplete#sources#jedi#show_docstring = 1 
    let g:deoplete#sources#jedi#worker_threads = 2
'''

[[plugins]]
repo = 'junegunn/goyo.vim'
