[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = ['scala']

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rs', 'rust']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['ts']

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
